### ISSUE TITLE
Settings: the focused state of the "Encrypted Contact Page" button is invisible

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2469]
Add `box-shadow` for `#public-profile-indicator:focus-within`, something like:

```css
#public-profile-indicator:focus-within {
  box-shadow: 0 0 1px 1px Highlight;
}
```
