### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by softmoth** [FlowCrypt/flowcrypt-browser#4735]
Please revisit #1385, which was closed in 2019 with "maybe in a year or two".

Even having a text box under "Additional Settings" or "Experimental" to add css overrides would be enough to start with.

    #foo-selector { background-color: #222; color: #ccc; }

**Comment by tomholub** [comment]
Hello,

I'd rather it be auto detected as in https://www.ajaypalcheema.com/dark-mode-js/ , else nearly nobody will take advantage of it, which would be 

But that does increase the need to do it more properly, ensuring that information on the page remains readable, even if not pretty.

I forgot if we still allow inline css tags. If we don't, there would have to be a special css file for dark mode.

So unfortunately it will end up being more effort than outlined above.

I'll consider this for Q2 2023. If the implementation is simple and not too many things to fix, we may ship it at that time. It's still possible to get postponed further, if it turns out troublesome to implement.

Cheers,

**Comment by tomholub** [comment]
I see pretty good results with this combo

```css
  html {filter: invert(100%) hue-rotate(180deg);background:black}
img {filter: invert(100%) hue-rotate(180deg) !important;}
video {filter: invert(100%) hue-rotate(180deg) !important;}
```

It inverts the luminosity without inverting colors. That means relative contrast of all items remains unaffected.
