### ISSUE TITLE
option to forget pass phrase anytime - if only in session

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#963]
should be as a part of the gmail ui (maybe on top)

https://mail.google.com/mail/u/0/#sent/15ffa1ab59b31ea2

**Comment by tomholub** [comment]
Better to show as a part of the pgp_block ui

**Comment by tomholub** [comment]
Maybe some sort of UI that shows eye / crossed eye Android icon

When clicked to forget pass phrase, a message should broadcast to all frames to forget it & reload

**Comment by tomholub** [comment]
css

```css
.cryptup_convo_button:not(:first-child) { margin-left: 5px; }
```
